name: dataflow
version: 0.0.0
synopsis: optimizing dataflow compiler

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - DeriveFunctor
  - ExistentialQuantification
  - FlexibleInstances
  - GADTs
  - PatternSynonyms
  - StandaloneDeriving

executable:
  name: dataflow
  main: Main.hs
  source-dirs: src
  dependencies:
    - base
    - containers
