name: dataflow
version: 0.0.0
synopsis: optimizing dataflow compiler

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - DeriveFunctor
  - ExistentialQuantification
  - FlexibleInstances
  - GADTs
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - ViewPatterns

ghc-options: >-
  -Wall
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns

executable:
  main: Main.hs
  source-dirs: src
  dependencies:
    - base
    - containers
